name: create plant uml png to wiki
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  update:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: render plant urml
        uses: frederikheld/render-plantuml-to-wiki-action@v1.0.1
        with:
          WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}
          INPUT_DIR: '.'
          OUTPUT_DIR: '/plantumls'

